### PR TITLE
shopping cart ui complete

### PR DESCRIPTION
**Pull request by broach44**
- Completes issue #69 
- Simple UI setup complete to display cart items
- Sample placeholders to see view

### CODE REVIEW

**Comment by ghost** [comment]
💯 👍

**Comment by jthielman** [comment]
So...it looks like the grey background and the line between the product info and the buttons on the cards is extending out into the drop shadow.  Do we want that?
It looks like there's some weird padding/negative margin stuff going on with the card footer div.

**Comment by broach44** [comment]
The div was outside the card body and needed to be inside, i fixed on the next PR because it wouldn't let me checkout to other branch without losing changes

**Comment by jthielman** [comment]
💯  + 👍

**Pull request merged**
